CREATE USER 'farmacia'@'localhost' IDENTIFIED BY '@farmaciaSV';
GRANT USAGE ON *.* TO 'farmacia'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `basefarmacia`.* TO 'farmacia'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'farmacia'@'localhost';