/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.ImageIcon;
import seguridad.Usuario;

/**
 *
 * @author GuillePC
 */
public class Menu extends javax.swing.JFrame {
      private static Usuario user;//variable global del usuario logeado

    /**
     * Creates new form Menup
     */

      
     public Menu()
     {
           initComponents();
        this.user=user;//Se asigna el usuaario que hizo login
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/índice.png")).getImage());
     
     }
    
    
     public Menu(Usuario user) {//metodo constructor que recibe el usuario logeados
        initComponents();
        this.user=user;//Se asigna el usuaario que hizo login
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/índice.png")).getImage());
        
    }

    
     public void seguridad(){
        System.out.println("nivel de acceso: "+user.getNivelAcceso());
        if(user.getNivelAcceso()==1){
            btnAddUser.setVisible(true);
            BtnProveedor.setVisible(true);
            btnNuevacompra.setVisible(true);
            btnInventario.setVisible(true);
            btnEstadisticas.setVisible(true);
        }else if(user.getNivelAcceso()==2){
            btnAddUser.setVisible(false);
            BtnProveedor.setVisible(false);
            btnNuevacompra.setVisible(true);
            btnInventario.setVisible(true);
            btnEstadisticas.setVisible(false);        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInventario = new javax.swing.JButton();
        BtnProveedor = new javax.swing.JButton();
        btnNuevacompra = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMedicamento = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMinimumSize(new java.awt.Dimension(1400, 185));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 185));
        getContentPane().setLayout(null);

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaBlanco.png"))); // NOI18N
        btnInventario.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Inventario</h2>\n\t</div>\n</body>\n</html>");
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaNegro.png"))); // NOI18N
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario);
        btnInventario.setBounds(180, 40, 70, 70);

        BtnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EquipoProveedorBlanco.png"))); // NOI18N
        BtnProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Proveedores<h2>\n\t</div>\n</body>\n</html>");
        BtnProveedor.setBorderPainted(false);
        BtnProveedor.setContentAreaFilled(false);
        BtnProveedor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EquipoProveedorNegro.png"))); // NOI18N
        BtnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnProveedor);
        BtnProveedor.setBounds(860, 50, 80, 50);

        btnNuevacompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AñadirCarritoBlanco.png"))); // NOI18N
        btnNuevacompra.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Nueva Compra</h2>\n\t</div>\n</body>\n</html>");
        btnNuevacompra.setBorderPainted(false);
        btnNuevacompra.setContentAreaFilled(false);
        btnNuevacompra.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AñadirCarritoNegro.png"))); // NOI18N
        btnNuevacompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevacompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevacompra);
        btnNuevacompra.setBounds(460, 40, 70, 80);

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EstadisticasBlanco.png"))); // NOI18N
        btnEstadisticas.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Estadísticas</h2>\n\t</div>\n</body>\n</html>");
        btnEstadisticas.setBorderPainted(false);
        btnEstadisticas.setContentAreaFilled(false);
        btnEstadisticas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EstadisticasNegro.png"))); // NOI18N
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstadisticas);
        btnEstadisticas.setBounds(750, 40, 70, 73);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar Sesion.png"))); // NOI18N
        btnCerrar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cerrar Programa</h2>\n\t</div>\n</body>\n</html>");
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar Sesion Select.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(1280, 30, 50, 50);

        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioBlanco.png"))); // NOI18N
        btnAddUser.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Añadir Usuario</h2>\n\t</div>\n</body>\n</html>");
        btnAddUser.setBorderPainted(false);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioNegro.png"))); // NOI18N
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddUser);
        btnAddUser.setBounds(1050, 40, 80, 70);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(0, 10, 150, 130);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cerrar Sesión");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1250, 80, 110, 30);

        btnMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MaletinBlanco.png"))); // NOI18N
        btnMedicamento.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Medicamentos</h2>\n\t</div>\n</body>\n</html>");
        btnMedicamento.setBorderPainted(false);
        btnMedicamento.setContentAreaFilled(false);
        btnMedicamento.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MaletinNegro.png"))); // NOI18N
        btnMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicamento);
        btnMedicamento.setBounds(260, 40, 80, 73);

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CarritoComprasBlanco.png"))); // NOI18N
        btnCompras.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Compras</h2>\n\t</div>\n</body>\n</html>");
        btnCompras.setBorderPainted(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CarritoComprasNegro.png"))); // NOI18N
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompras);
        btnCompras.setBounds(360, 40, 80, 70);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentasDineroBlanco.png"))); // NOI18N
        btnVentas.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Ventas</h2>\n\t</div>\n</body>\n</html>");
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentasDineroNegro.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas);
        btnVentas.setBounds(540, 30, 97, 80);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClientesBlanco.png"))); // NOI18N
        btnClientes.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Clientes\n</h2>\n\t</div>\n</body>\n</html>");
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClientesNegro.png"))); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(960, 40, 70, 73);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioNuevoBlanco.png"))); // NOI18N
        btnUsuarios.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Usuarios</h2>\n\t</div>\n</body>\n</html>");
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioNuevoNegro.png"))); // NOI18N
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios);
        btnUsuarios.setBounds(1150, 40, 80, 70);

        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NVentaBlanco.png"))); // NOI18N
        btnNuevaVenta.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Nueva Venta</h2>\n\t</div>\n</body>\n</html>");
        btnNuevaVenta.setBorderPainted(false);
        btnNuevaVenta.setContentAreaFilled(false);
        btnNuevaVenta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NVentaNegro.png"))); // NOI18N
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevaVenta);
        btnNuevaVenta.setBounds(630, 30, 97, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wpblue.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        Inventario in = new Inventario(user);
        in.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void BtnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProveedorActionPerformed
        Proveedores Provee = new Proveedores(user);
        Provee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnProveedorActionPerformed

    private void btnNuevacompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevacompraActionPerformed
        NuevaCompra nuev = new NuevaCompra(user);
        nuev.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnNuevacompraActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed

    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        inicio otro = new inicio();
        otro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed

    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentoActionPerformed

        Medicamento med = new Medicamento(user);
        med.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnMedicamentoActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        Compras Comprass = new Compras(user);
        Comprass.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        Clientes cliente = new Clientes(user);
        cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
       Ventas vent = new Ventas(user);
       vent.setVisible(true);
       this.setVisible(false);
               
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        NuevaVenta NVenta = new NuevaVenta(user);
        NVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {               
                new Menu(user).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProveedor;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMedicamento;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnNuevacompra;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
