/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import seguridad.Acceso;
import seguridad.ManejoUsuarios;
import seguridad.Usuario;

/**
 *
 * @author USUARIO
 */
public class Usuarios extends javax.swing.JInternalFrame {
    private ManejoUsuarios manejador = new ManejoUsuarios();
    DefaultTableModel modeloTabla;
    ArrayList<Usuario> usuarios;
    ArrayList<Acceso> accesos;
    
    
    /**
     * Creates new form Inven
     */
    public Usuarios() {
        initComponents();
        usuarios = manejador.getUsuarios();
        modeloTabla =  (DefaultTableModel) jTable2.getModel();
        for (Iterator<Usuario> iterator = usuarios.iterator(); iterator.hasNext();) {
            Usuario next = iterator.next();
            modeloTabla.addRow(new String[]{next.getUserId()+"", next.getUserName(), next.getNivelAcceso()==1?"Administrador":"usuario"});
        } 
        BuscarInventario.setVisible(false);
        accesos = manejador.getAcceso();
        for (Acceso acceso : accesos) {
            jComboBox1.addItem(acceso.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        BuscarInventario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombrecomercial = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Btnadd1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnBuscar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setEnabled(false);
        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(1030, 500));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPasswordField1.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Contraseña del usuario</h2>\n\t</div>\n</body>\n</html>");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(710, 240, 230, 22);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Usuarios");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 0, 240, 41);
        jPanel1.add(BuscarInventario);
        BuscarInventario.setBounds(10, 60, 290, 30);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Añadir Usuario</h2>\n\t</div>\n</body>\n</html>");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search select.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(500, 70, 40, 40);

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("id");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(670, 120, 40, 20);

        txt_id.setEnabled(false);
        jPanel1.add(txt_id);
        txt_id.setBounds(710, 120, 230, 20);

        txt_nombrecomercial.setEnabled(false);
        jPanel1.add(txt_nombrecomercial);
        txt_nombrecomercial.setBounds(710, 150, 230, 20);

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Nombre:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 150, 120, 20);

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Guardar");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(880, 440, 60, 20);

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Contraseña");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(600, 240, 150, 20);

        Btnadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/saveok.jpg"))); // NOI18N
        Btnadd1.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Guardar</h2>\n\t</div>\n</body>\n</html>");
        Btnadd1.setBorderPainted(false);
        Btnadd1.setContentAreaFilled(false);
        Btnadd1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/saveselgrande.jpg"))); // NOI18N
        Btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnadd1ActionPerformed(evt);
            }
        });
        jPanel1.add(Btnadd1);
        Btnadd1.setBounds(880, 380, 60, 60);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Acceso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 110, 530, 380);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Detalle Usuario");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(720, 70, 270, 41);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(710, 190, 230, 22);

        jPasswordField2.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Contraseña del usuario</h2>\n\t</div>\n</body>\n</html>");
        jPasswordField2.setEnabled(false);
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(710, 300, 230, 22);

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Contraseña");
        jLabel18.setEnabled(false);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(600, 300, 150, 20);

        jPasswordField3.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Contraseña del usuario</h2>\n\t</div>\n</body>\n</html>");
        jPasswordField3.setEnabled(false);
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField3);
        jPasswordField3.setBounds(710, 330, 230, 22);

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("Repita contraseña");
        jLabel20.setEnabled(false);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(560, 330, 150, 20);

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Acceso");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(600, 180, 210, 41);

        jCheckBox1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jCheckBox1.setText("Cambio de Clave");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(603, 270, 310, 29);

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/selectusuario.jpg"))); // NOI18N
        btnBuscar1.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Añadir Usuario</h2>\n\t</div>\n</body>\n</html>");
        btnBuscar1.setBorderPainted(false);
        btnBuscar1.setContentAreaFilled(false);
        btnBuscar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search select.png"))); // NOI18N
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar1);
        btnBuscar1.setBounds(460, 70, 40, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         if (jTable2.getSelectedRow() != -1) {
            int fila =jTable2.getSelectedRow();
             Usuario user = usuarios.get(fila);
             txt_id.setText(user.getUserId()+"");
             txt_nombrecomercial.setText(user.getUserName());
         }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void Btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnadd1ActionPerformed
        if (jTable2.getSelectedRow() != -1) {
            int fila =jTable2.getSelectedRow();
            if (jCheckBox1.isSelected()) {
                if(jPasswordField2.getText().equals(jPasswordField3.getText())){
                    boolean resutl = manejador.cambiarConstraseña(usuarios.get(fila), jPasswordField1.getText(), jPasswordField2.getText());
                    if (!resutl) {
                        JOptionPane.showMessageDialog(this, "Error no se pudo actualizar contraseñas,  ¿Ingreso una contraseña antigua valida?","ERROR",JOptionPane.ERROR_MESSAGE);//se informa que el usuario no existe
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Las conraseñas no coinciden","ERROR",JOptionPane.ERROR_MESSAGE);//se informa que el usuario no existe
                }
            }
            int combo = jComboBox1.getSelectedIndex();
            boolean acc =manejador.modificarAcceso(usuarios.get(fila), accesos.get(combo).getId());
            if (!acc) {
                JOptionPane.showMessageDialog(this, "Error no se pudo actualizar acceso","ERROR",JOptionPane.ERROR_MESSAGE);//se informa que el usuario no existe
            }
            JOptionPane.showMessageDialog(this, "Informacion Actualizada","INFORMACION",JOptionPane.INFORMATION_MESSAGE);//se informa que el usuario no existe
        }
    }//GEN-LAST:event_Btnadd1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jPasswordField2.setEnabled(true);
            jPasswordField3.setEnabled(true);
        }else{
            jPasswordField2.setEnabled(false);
            jPasswordField3.setEnabled(false);
            
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed

    }//GEN-LAST:event_btnBuscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnadd1;
    private javax.swing.JTextField BuscarInventario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombrecomercial;
    // End of variables declaration//GEN-END:variables
}
